package com.mergano.gui;

import com.mergano.core.Authenticate;
import static com.mergano.core.ClearGC.ClearGarbageCollection;
import com.mergano.core.Encryption;
import com.mergano.core.TextFieldLimit;
import com.mergano.core.bean.LoginBean;
import com.mergano.core.bean.StatusBean;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

public class Login extends javax.swing.JFrame {

    public static boolean session;
    LoginBean login;

    public Login() {
        initComponents();
        auth_username_input.setDocument(new TextFieldLimit(25));
        auth_password_input.setDocument(new TextFieldLimit(25));
        login = new LoginBean();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgot_password_dialog = new javax.swing.JDialog();
        forgot_title_box = new javax.swing.JPanel();
        forgot_title = new javax.swing.JLabel();
        forgot_input_box = new javax.swing.JPanel();
        forgot_text_input = new javax.swing.JTextField();
        forgot_submit_box = new javax.swing.JPanel();
        forgot_submit_btn = new javax.swing.JButton();
        auth_header = new javax.swing.JPanel();
        auth_header_image = new javax.swing.JLabel();
        auth_title = new javax.swing.JLabel();
        auth_body = new javax.swing.JPanel();
        auth_input_box = new javax.swing.JPanel();
        auth_input_layout_box = new javax.swing.JPanel();
        auth_username_label_box = new javax.swing.JPanel();
        auth_username_label = new javax.swing.JLabel();
        auth_username_box = new javax.swing.JPanel();
        auth_username_input = new javax.swing.JTextField();
        auth_password_label_box = new javax.swing.JPanel();
        auth_password_label = new javax.swing.JLabel();
        auth_password_box = new javax.swing.JPanel();
        auth_password_input = new javax.swing.JPasswordField();
        auth_error_box = new javax.swing.JPanel();
        auth_error_message_label = new javax.swing.JLabel();
        auth_footer = new javax.swing.JPanel();
        auth_signin_btn = new javax.swing.JButton();
        auth_cancel_btn = new javax.swing.JButton();

        forgot_password_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        forgot_password_dialog.setTitle("Forgot password");
        forgot_password_dialog.setLocation(new java.awt.Point(0, 0));
        forgot_password_dialog.setMaximumSize(new java.awt.Dimension(400, 150));
        forgot_password_dialog.setMinimumSize(new java.awt.Dimension(400, 150));
        forgot_password_dialog.setName("forgot_password_dialog"); // NOI18N
        forgot_password_dialog.setPreferredSize(new java.awt.Dimension(400, 150));
        forgot_password_dialog.setResizable(false);
        forgot_password_dialog.setSize(new java.awt.Dimension(400, 150));
        forgot_password_dialog.setType(java.awt.Window.Type.POPUP);
        forgot_password_dialog.getContentPane().setLayout(new javax.swing.BoxLayout(forgot_password_dialog.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        forgot_title_box.setName("forgot_title_box"); // NOI18N

        forgot_title.setText("Enter your email address account.");
        forgot_title.setName("forgot_title"); // NOI18N
        forgot_title_box.add(forgot_title);

        forgot_password_dialog.getContentPane().add(forgot_title_box);

        forgot_input_box.setName("forgot_input_box"); // NOI18N

        forgot_text_input.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        forgot_text_input.setName("forgot_text_input"); // NOI18N
        forgot_text_input.setPreferredSize(new java.awt.Dimension(350, 30));
        forgot_input_box.add(forgot_text_input);

        forgot_password_dialog.getContentPane().add(forgot_input_box);

        forgot_submit_box.setName("forgot_submit_box"); // NOI18N

        forgot_submit_btn.setText("Submit");
        forgot_submit_btn.setName("forgot_submit_btn"); // NOI18N
        forgot_submit_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        forgot_submit_box.add(forgot_submit_btn);

        forgot_password_dialog.getContentPane().add(forgot_submit_box);

        forgot_password_dialog.getAccessibleContext().setAccessibleDescription("");
        forgot_password_dialog.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mergano/Bundle"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(500, 450));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));

        auth_header.setName("auth_header"); // NOI18N
        auth_header.setLayout(new java.awt.BorderLayout());

        auth_header_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auth_header_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/login.png"))); // NOI18N
        auth_header_image.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        auth_header_image.setFocusable(false);
        auth_header_image.setName("auth_header_image"); // NOI18N
        auth_header.add(auth_header_image, java.awt.BorderLayout.NORTH);

        auth_title.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        auth_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auth_title.setText("System Authentication");
        auth_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        auth_title.setName("auth_title"); // NOI18N
        auth_title.setPreferredSize(new java.awt.Dimension(178, 45));
        auth_header.add(auth_title, java.awt.BorderLayout.CENTER);

        getContentPane().add(auth_header, java.awt.BorderLayout.NORTH);

        auth_body.setName("auth_body"); // NOI18N
        auth_body.setPreferredSize(new java.awt.Dimension(100, 160));
        auth_body.setLayout(new java.awt.BorderLayout(0, 10));

        auth_input_box.setMaximumSize(new java.awt.Dimension(500, 150));
        auth_input_box.setMinimumSize(new java.awt.Dimension(500, 150));
        auth_input_box.setName("auth_input_box"); // NOI18N
        auth_input_box.setPreferredSize(new java.awt.Dimension(500, 150));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        auth_input_box.setLayout(flowLayout1);

        auth_input_layout_box.setMinimumSize(new java.awt.Dimension(300, 128));
        auth_input_layout_box.setName("auth_input_layout_box"); // NOI18N
        auth_input_layout_box.setLayout(new javax.swing.BoxLayout(auth_input_layout_box, javax.swing.BoxLayout.PAGE_AXIS));

        auth_username_label_box.setName("auth_username_label_box"); // NOI18N
        auth_username_label_box.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        auth_username_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        auth_username_label.setText("Username");
        auth_username_label.setName("auth_username_label"); // NOI18N
        auth_username_label_box.add(auth_username_label);

        auth_input_layout_box.add(auth_username_label_box);

        auth_username_box.setName("auth_username_box"); // NOI18N
        auth_username_box.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        auth_username_input.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        auth_username_input.setName("auth_username_input"); // NOI18N
        auth_username_input.setPreferredSize(new java.awt.Dimension(300, 30));
        auth_username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auth_username_inputActionPerformed(evt);
            }
        });
        auth_username_box.add(auth_username_input);

        auth_input_layout_box.add(auth_username_box);

        auth_password_label_box.setName("auth_password_label_box"); // NOI18N
        auth_password_label_box.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        auth_password_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        auth_password_label.setText("Password");
        auth_password_label.setName("auth_password_label"); // NOI18N
        auth_password_label_box.add(auth_password_label);

        auth_input_layout_box.add(auth_password_label_box);

        auth_password_box.setName("auth_password_box"); // NOI18N
        auth_password_box.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        auth_password_input.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        auth_password_input.setName("auth_password_input"); // NOI18N
        auth_password_input.setPreferredSize(new java.awt.Dimension(300, 30));
        auth_password_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                auth_password_inputKeyPressed(evt);
            }
        });
        auth_password_box.add(auth_password_input);

        auth_input_layout_box.add(auth_password_box);

        auth_error_box.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        auth_error_box.setName("auth_error_box"); // NOI18N
        auth_error_box.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        auth_error_message_label.setForeground(new java.awt.Color(255, 0, 0));
        auth_error_message_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auth_error_message_label.setToolTipText("");
        auth_error_message_label.setName("auth_error_message_label"); // NOI18N
        auth_error_box.add(auth_error_message_label);

        auth_input_layout_box.add(auth_error_box);
        auth_error_box.getAccessibleContext().setAccessibleName("");

        auth_input_box.add(auth_input_layout_box);

        auth_body.add(auth_input_box, java.awt.BorderLayout.NORTH);

        auth_footer.setMinimumSize(new java.awt.Dimension(0, 0));
        auth_footer.setName("auth_footer"); // NOI18N
        auth_footer.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 22, 0);
        flowLayout2.setAlignOnBaseline(true);
        auth_footer.setLayout(flowLayout2);

        auth_signin_btn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        auth_signin_btn.setText("Sign in");
        auth_signin_btn.setName("auth_signin_btn"); // NOI18N
        auth_signin_btn.setPreferredSize(new java.awt.Dimension(140, 35));
        auth_signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auth_signin_btnActionPerformed(evt);
            }
        });
        auth_footer.add(auth_signin_btn);

        auth_cancel_btn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        auth_cancel_btn.setText("Cancel");
        auth_cancel_btn.setName("auth_cancel_btn"); // NOI18N
        auth_cancel_btn.setPreferredSize(new java.awt.Dimension(140, 35));
        auth_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auth_cancel_btnActionPerformed(evt);
            }
        });
        auth_footer.add(auth_cancel_btn);

        auth_body.add(auth_footer, java.awt.BorderLayout.CENTER);

        getContentPane().add(auth_body, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void auth_signin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auth_signin_btnActionPerformed
        this.signin();
    }//GEN-LAST:event_auth_signin_btnActionPerformed

    private void auth_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auth_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_auth_cancel_btnActionPerformed

    private void auth_password_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auth_password_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.signin();
        }
    }//GEN-LAST:event_auth_password_inputKeyPressed

    private void auth_username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auth_username_inputActionPerformed
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.getFocusOwner().transferFocus();
    }//GEN-LAST:event_auth_username_inputActionPerformed

    private void signin() {
        final String user;
        final char[] pwd;
        user = auth_username_input.getText();
        pwd = auth_password_input.getPassword();
        if (user.length() != 0 && pwd.length != 0) {
            String encryptedUsername = Encryption.encrypt(user);
            String encryptedPassword = Encryption.encrypt(String.valueOf(pwd));
            //String decryptedPassword = Encryption.decrypt("tm+m/bhBMk+fc6a/2ScztLdY+PzGUhih1oNUiGKv97lfHAeiRclBKyU6Wi2elCri");
            Authenticate auth = new Authenticate();
            int flag = auth.VerifyUser(encryptedUsername, encryptedPassword);

            switch (flag) {
                case 0: // NO INTERNET CONNECTION
                    session = false;
                    SetCurrentSession(session);
                    ResetLoginInput("No internet connection");
                    break; //optional
                case 1: // LOGIN SUCCESSFUL AS ADMINISTRATOR LEVEL
                    SetCurrentSession(true);
                    ResetLoginInput("");
                    LoginAdminProcess(LoginBean.getUserTxt());
                    break;
                case 2: // LOGIN SUCCESGULL AS USER LEVEL
                    SetCurrentSession(true);
                    ResetLoginInput("");
                    LoginUserProcess(LoginBean.getUserTxt());
                    break;
                case 3: // LOGIN SUCCESGULL AS AGENT LEVEL
                    SetCurrentSession(true);
                    ResetLoginInput("");
                    LoginAgentProcess(LoginBean.getUserTxt());
                    break;
                case 4: // LOGIN SUCCESGULL AS DRIVER LEVEL
                    SetCurrentSession(true);
                    ResetLoginInput("");
                    LoginDriverProcess(LoginBean.getUserTxt());
                    break;
                case 5: // LOGIN SUCCESGULL AS DEBUG MODE
                    SetCurrentSession(true);
                    ResetLoginInput("");
                    LoginDebugModeProcess(LoginBean.getUserTxt());
                    break;
                case 6: // LOGIN FAILED WRONG USER OR PASSWORD
                    SetCurrentSession(false);
                    ResetLoginInput("Incorrect username or password");
                    break;
                case -2: // LOGIN FAILED USER EXCEED THE LOGIN ATTEMPS
                    SetCurrentSession(false);
                    ResetLoginInput("System temporary locked. please contact your administrator.");
                    break;
            }
        } else {
            ResetLoginInput("Please fill in username or password completely.");
        }
    }

    private void ResetLoginInput(String err) {
        auth_error_message_label.setText(err);
        auth_username_input.setText("");
        auth_password_input.setText("");
    }

    private void LoginAdminProcess(String u) {
        this.dispose();
        Main m = new Main();
        Main.user_box.setText(u);
        Main.user_box.setForeground(Color.red);
        SetUpStatusBar();
        ClearLoginPassword();
        m.pack();
        m.setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        m.setExtendedState(m.getExtendedState() | Main.MAXIMIZED_BOTH);
        m.setVisible(true);
    }

    private void LoginUserProcess(String u) {
        this.dispose();
        Main m = new Main();
        Main.user_box.setText(u);
        Main.user_box.setForeground(Color.GREEN);
        m.manager_user_menuitem.setEnabled(false);
        m.database_menu.setEnabled(false);
        m.database_panel.setEnabled(false);
        m.database_menuitem.setEnabled(false);
        m.body.setEnabledAt(5, false);
        m.data_button_wel.setEnabled(false);
        m.User_button.setEnabled(false);
        m.mai_button_wel.setEnabled(false);
        SetUpStatusBar();
        ClearLoginPassword();
        m.pack();
        m.setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        m.setExtendedState(m.getExtendedState() | Main.MAXIMIZED_BOTH);
        m.setVisible(true);
    }

    private void LoginAgentProcess(String u) {
        this.dispose();
        Main m = new Main();
        Main.user_box.setText(u);
        Main.user_box.setForeground(Color.MAGENTA);
        m.manager_user_menuitem.setEnabled(false);
        m.database_menu.setEnabled(false);
        m.database_panel.setEnabled(false);
        m.database_menuitem.setEnabled(false);
        m.body.setEnabledAt(2, false);
        m.body.setEnabledAt(5, false);
        m.sm_button_wel.setEnabled(false);
        m.management_panel.setEnabled(false);
        m.data_button_wel.setEnabled(false);
        m.User_button.setEnabled(false);
        m.mai_button_wel.setEnabled(false);
        SetUpStatusBar();
        ClearLoginPassword();
        m.pack();
        m.setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        m.setExtendedState(m.getExtendedState() | Main.MAXIMIZED_BOTH);
        m.setVisible(true);
    }

    private void LoginDriverProcess(String u) {
        this.dispose();
        Main m = new Main();
        Main.user_box.setText(u);
        Main.user_box.setForeground(Color.ORANGE);
        m.manager_user_menuitem.setEnabled(false);
        m.database_menu.setEnabled(false);
        m.database_panel.setEnabled(false);
        m.database_menuitem.setEnabled(false);
        m.body.setEnabledAt(2, false);
        m.body.setEnabledAt(3, false);
        m.body.setEnabledAt(5, false);
        m.sm_button_wel.setEnabled(false);
        m.management_panel.setEnabled(false);
        m.order_panel.setEnabled(false);
        m.data_button_wel.setEnabled(false);
        m.User_button.setEnabled(false);
        m.mai_button_wel.setEnabled(false);
        SetUpStatusBar();
        ClearLoginPassword();
        m.pack();
        m.setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        m.setExtendedState(m.getExtendedState() | Main.MAXIMIZED_BOTH);
        m.setVisible(true);
    }

    private void LoginDebugModeProcess(String u) {
        this.dispose();
        Main m = new Main();
        Main.user_box.setText(u);
        Main.user_box.setForeground(Color.RED);
        SetUpStatusBar();
        ClearLoginPassword();
        m.pack();
        m.setIconImage(new ImageIcon(getClass().getResource("/com/mergano/gui/_static/pic/icon.png")).getImage());
        m.setExtendedState(m.getExtendedState() | Main.MAXIMIZED_BOTH);
        m.setVisible(true);
    }

    private void SetUpStatusBar() {
        Main.status_box.setText(StatusBean.getStatus());
        Main.db_name_box.setText(StatusBean.getDbName());
        Main.db_type_box.setText(StatusBean.getDbType());
        Main.port_box.setText(StatusBean.getPort());
        Main.url_box.setText(StatusBean.getUrl());
    }

    private void ClearLoginPassword() {
        // Clear Password after finished login process to prevent unauthorized access
        login.setPassword("");
        // To decrease the memory usage by cleanup unused garbage collection
        ClearGarbageCollection();
    }

    public void SetCurrentSession(boolean s) {
        session = s;
    }

    public static boolean CurrentSession() {
        return session;
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auth_body;
    private javax.swing.JButton auth_cancel_btn;
    private javax.swing.JPanel auth_error_box;
    private javax.swing.JLabel auth_error_message_label;
    private javax.swing.JPanel auth_footer;
    private javax.swing.JPanel auth_header;
    private javax.swing.JLabel auth_header_image;
    private javax.swing.JPanel auth_input_box;
    private javax.swing.JPanel auth_input_layout_box;
    private javax.swing.JPanel auth_password_box;
    private javax.swing.JPasswordField auth_password_input;
    private javax.swing.JLabel auth_password_label;
    private javax.swing.JPanel auth_password_label_box;
    private javax.swing.JButton auth_signin_btn;
    private javax.swing.JLabel auth_title;
    private javax.swing.JPanel auth_username_box;
    private javax.swing.JTextField auth_username_input;
    private javax.swing.JLabel auth_username_label;
    private javax.swing.JPanel auth_username_label_box;
    private javax.swing.JPanel forgot_input_box;
    private javax.swing.JDialog forgot_password_dialog;
    private javax.swing.JPanel forgot_submit_box;
    private javax.swing.JButton forgot_submit_btn;
    private javax.swing.JTextField forgot_text_input;
    private javax.swing.JLabel forgot_title;
    private javax.swing.JPanel forgot_title_box;
    // End of variables declaration//GEN-END:variables
}
